### PR TITLE
tickers for all markets

### PR DESCRIPTION
**Pull request by omid455**
Please include this function as added above, tickers_for_all_pairs_by_markets, It shows all the tickers at once and eliminates the need to loop through a list to get multiple tickers.

### CODE REVIEW

**Comment by fasetto** [comment]
Thank you for the contribution. 🙂

**Comment by omid455** [comment]
> Thank you for the contribution. 🙂

My pleasure,and thank you for accepting it.

**Comment by omid455** [comment]
sorry to bother you again, would you please update the PIP package as well? Thanks

**Comment by fasetto** [comment]
Done.

**Pull request merged**
